### ISSUE TITLE
Add Psalm and document arguments for DTO constructors

### ISSUE THREAD

**Issue by flumonion** [stock2shop/share#18]
@DustinS2S @mannyqi this is a good first issue to tackle w.r.t Psalm and static analysis.

**Comment by flumonion** [comment]
@DustinS2S I have merged #32 .

However, whilst using the types on another project which requires share, I realised there are a couple of mistakes.
Please create a new branch to address these.

## Allow missing array properties:-

Current:
```php
* @psalm-type TypeChannelProduct = array{
*     id?: int|null,
*     variants: TypeChannelVariant
* }
```
Should be:

```php
* @psalm-type TypeChannelProduct = array{
*     id?: int|null,
*     variants?: TypeChannelVariant
* }
```
You can test this by seeing if this gives you an error:

```php
$cp = new DTO\ChannelProduct([]);
```

i.e. creating a blank new DTO in most cases should be allowed.

## Type arrays correctly:-

Current:
```php
* @psalm-type TypeChannelProduct = array{
*     id?: int|null,
*     variants: TypeChannelVariant
* }
```

Should be:
```php
* @psalm-type TypeChannelProduct = array{
*     id?: int|null,
*     variants?: array<int, TypeChannelVariant>
* }
```

In the above example, the variants property is an array of `TypeChannelVariant`.

Tested by:-

```php
$cp = new DTO\ChannelProduct([
   'variants' => [
                        [
                            'id' => '1'
                        ],
                        [
                            'id' => '2'
                        ]
                    ]
]);
```

Please make these changes.
It makes sense for you to try this out yourself.
You could create a types file in the test directory where you instantiate all DTO's without params to ensure you get no type errors when Psalm runs.
Perhaps add in some checks to ensure that the array issue above is not happening...

**Comment by DustinS2S** [comment]
Update to fix types for sub classes and include a static test 
[PR](https://github.com/stock2shop/share/pull/35)

**Comment by DustinS2S** [comment]
All psalm types for DTO's has been done.
Psalm appears to be functioning correctly.

Closing the issue, should there be a requirement to add or amend any Psalm types or include any `@psalm-suppress` flags, issue can be reopened.
